# Generated by Django 2.2.5 on 2020-05-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('fish_id', models.AutoField(primary_key=True, serialize=False)),
                ('fish_name', models.TextField()),
                ('fish_value', models.IntegerField(blank=True, null=True)),
                ('fish_location', models.TextField()),
            ],
            options={
                'verbose_name': 'Fish',
                'verbose_name_plural': 'Fishes',
                'db_table': 'Fish',
                'managed': False,
            },
        ),
    ]
