# Generated by Django 2.2.5 on 2020-05-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_fish_fish_caught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='fish_caught',
        ),
    ]
