# Generated by Django 2.2.5 on 2020-05-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_bug_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_caught',
            field=models.BooleanField(default=False),
        ),
    ]
