# Generated by Django 2.2.5 on 2020-05-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_default_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='bug_caught',
        ),
    ]
